app = "magic-services"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "testing"
  PYTHONUNBUFFERED = "1"
  GOOGLE_CREDENTIALS_PATH = "./credentials/google.json"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = false

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/"
